### ISSUE TITLE
[Question] Additional Distance Metrics

### ISSUE THREAD

**Issue by Mpicca** [ing-bank/EntityMatchingModel#15]
Will there be more distance metrics added such as Levenshtein, Iterative Substring, Double Metaphone..etc 
I prefer to leverage this library due to spark language compatibility and it's speed but wish we had more distance metrics like in the name_matching library from DeNederlandscheBank

**Comment by mbaak** [comment]
Levenshtein, Jaro and all multiple ratio distances of the rapidfuzz library are already used as features by the supervised model. See:
https://github.com/ing-bank/EntityMatchingModel/blob/main/emm/features/pandas_feature_extractor.py#L101

In principle I'm okay with other metrics as well, but the added value needs to be shown. Especially b/c there are strong correlations between them, and - as it turns out - in practice we see that the string-distance features we use now (*on top of* cosine similary values from the indexers) do not add a lot of extra discrimination power, but are expensive to calculate.
